# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/aquasecurity/trivy"
  version "0.45.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.8/trivy_0.45.8_macOS-64bit.tar.gz"
      sha256 "a46a8a86d48a0fe5606acda1cef11aeb4e3bca8592576c34efa23e5baa521a9e"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.8/trivy_0.45.8_macOS-ARM64.tar.gz"
      sha256 "dd58f99306882d24e15980f458e6f8e1665e88c95cbc691b687e223e67b2652f"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.8/trivy_0.45.8_Linux-ARM64.tar.gz"
      sha256 "a8be3192d3e48b4fd97b0c2fc3eed4bebb0cf28283798f62c411df307ebd5e6e"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.8/trivy_0.45.8_Linux-64bit.tar.gz"
      sha256 "b3ccd6315530a21bf34aa890307c76acb1106e74639092d2c1f677d7b3da5288"

      def install
        bin.install "trivy"
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
