# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/aquasecurity/trivy"
  version "0.45.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.7/trivy_0.45.7_macOS-64bit.tar.gz"
      sha256 "b0bdec7fc191803226ebb0fb52e4b32ee30bb547c28703a977931a1ce73c70cb"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.7/trivy_0.45.7_macOS-ARM64.tar.gz"
      sha256 "5d85d87af630f855d5ab13dd13109bd723163084eb4894acbb5b8e65b0ec0aaf"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.7/trivy_0.45.7_Linux-ARM64.tar.gz"
      sha256 "275036686c459fe44afb1336ba9b6ad93aa41ad36b4921be5ed4c7128f165a24"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikpivkin/trivy/releases/download/v0.45.7/trivy_0.45.7_Linux-64bit.tar.gz"
      sha256 "7eee54cc1287fc54c5dbb694e68dc3a2eb447f562bbef000f1047c41999567b5"

      def install
        bin.install "trivy"
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
